#!/usr/bin/env node

// Generated by CoffeeScript 1.12.4
(function() {
  var ffi, libpgnparser, ref;

  ref = require('ref');

  ffi = require('ffi');

  libpgnparser = ffi.Library('../../libpgnparser.so', {
    'parser': ['string', ['string', 'int', 'int']]
  });

  if (!!module.parent) {
    module.exports = libpgnparser.parser;
  } else {
    if (process.argv.length === 2) {
      console.log(libpgnparser.parser(ref.NULL_POINTER, 1, 1000000));
    } else {
      console.log(libpgnparser.parser(process.argv[2], 1, 1000));
    }
  }

}).call(this);
